# Generated by Django 3.2.6 on 2021-11-05 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shareledge', '0003_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
