# Generated by Django 3.2.6 on 2021-11-18 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shareledge', '0007_alter_article_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='contentImage',
            field=models.URLField(),
        ),
    ]
