# Generated by Django 3.2.6 on 2021-11-24 14:14

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shareledge', '0008_alter_article_contentimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='userGuidePoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('content', ckeditor.fields.RichTextField()),
            ],
        ),
    ]
